stages:
  - build
  - deploy

build:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: build
  script:
    - cd BackEnd
    - docker build -t mi-aplicacion .

deploy:
  image: debian:bullseye-slim
  stage: deploy
  before_script:
    - apt-get update && apt-get upgrade -y
    - apt-get install -y openssh-client
    - mkdir -p /root/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - || (echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-keygen -p -m PEM -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pem && ssh-add /root/.ssh/id_rsa.pem)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - apt-get update
    - apt-get install -y apt-transport-https ca-certificates curl gnupg lsb-release
    - curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
    - echo "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
    - apt-get update
    - apt-get install -y docker-ce docker-ce-cli containerd.io
    - docker build -t $DOCKER_USERNAME/mi-aplicacion:latest BackEnd
    - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - docker push $DOCKER_USERNAME/mi-aplicacion:latest
    - ssh -o StrictHostKeyChecking=no ubuntu@$MI_INSTANCIA_EC2 "sudo docker stop $(sudo docker ps -q --filter 'publish=8080') || true"
    - ssh -o StrictHostKeyChecking=no ubuntu@$MI_INSTANCIA_EC2 "sudo docker rm $(sudo docker ps -a -q --filter 'publish=8080') || true"
    - ssh -o StrictHostKeyChecking=no ubuntu@$MI_INSTANCIA_EC2 "sudo docker pull ${DOCKER_USERNAME}/mi-aplicacion:latest && sudo docker run -d -p 8080:8080 ${DOCKER_USERNAME}/mi-aplicacion:latest"




