stages:
  - build
  - deploy

build:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: build
  script:
    - cd BackEnd
    - docker build -t mi-aplicacion:$CI_COMMIT_SHA .

deploy:
  image: debian:bullseye-slim
  stage: deploy
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - chmod 600 /root/.ssh/id_rsa
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | tr -d '\r')
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag mi-aplicacion:$CI_COMMIT_SHA $DOCKER_USERNAME/mi-aplicacion:$CI_COMMIT_SHA
    - docker push $DOCKER_USERNAME/mi-aplicacion:$CI_COMMIT_SHA
    - ssh -o StrictHostKeyChecking=no ec2-user@$MI_INSTANCIA_EC2 'docker pull $DOCKER_USERNAME/mi-aplicacion:$CI_COMMIT_SHA && docker run -d -p 8080:8080 $DOCKER_USERNAME/mi-aplicacion:$CI_COMMIT_SHA'


