stages:
  - build
  - deploy

build:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: build
  script:
    - cd BackEnd
    - docker build -t mi-aplicacion .

deploy:
  stage: deploy
  before_script:
    - apk update && apk upgrade
    - apk add openssh-client
    - mkdir -p /root/.ssh
    - 'echo "$SSH_PRIVATE_KEY" > /root/.ssh/id_rsa'
    - 'chmod 600 /root/.ssh/id_rsa'
    - $ ssh-keygen -p -m PEM -f /root/.ssh/id_rsa
    - 'which ssh-agent || ( apk update && apk add openssh-client )' # Cambiado de apt-get a apk
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag mi-aplicacion $DOCKER_USERNAME/mi-aplicacion:latest
    - docker push $DOCKER_USERNAME/mi-aplicacion:latest
    - ssh -o StrictHostKeyChecking=no ec2-user@$MI_INSTANCIA_EC2 'docker pull $DOCKER_USERNAME/mi-aplicacion:latest && docker run -d -p 8080:8080 $DOCKER_USERNAME/mi-aplicacion:latest'




