stages:
  - build
  - deploy

build:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: build
  script:
    - cd BackEnd
    - docker build -t mi-aplicacion .

deploy:
  stage: deploy
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag mi-aplicacion $DOCKER_USERNAME/mi-aplicacion:latest
    - docker push $DOCKER_USERNAME/mi-aplicacion:latest
    - ssh -o StrictHostKeyChecking=no ec2-user@$MI_INSTANCIA_EC2 'docker pull $DOCKER_USERNAME/mi-aplicacion:latest && docker run -d -p 8080:8080 $DOCKER_USERNAME/mi-aplicacion:latest'




