stages:
  - build
  - deploy

build:
  image: docker:19.03.12
  services:
    - docker:19.03.12-dind
  stage: build
  script:
    - cd BackEnd
    - docker build -t mi-aplicacion .

deploy:
  image: debian:bullseye-slim
  stage: deploy
  before_script:
    - apt-get update && apt-get upgrade -y
    - apt-get install -y openssh-client
    - mkdir -p /root/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa
    - eval $(ssh-agent -s)
    # Intenta agregar la clave. Si falla, conviértela a PEM y luego agrégala.
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - || (echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-keygen -p -m PEM -f /root/.ssh/id_rsa > /root/.ssh/id_rsa.pem && ssh-add /root/.ssh/id_rsa.pem)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - docker tag mi-aplicacion $DOCKER_USERNAME/mi-aplicacion:latest
    - docker push $DOCKER_USERNAME/mi-aplicacion:latest
    - ssh -o StrictHostKeyChecking=no ec2-user@$MI_INSTANCIA_EC2 'docker pull $DOCKER_USERNAME/mi-aplicacion:latest && docker run -d -p 8080:8080 $DOCKER_USERNAME/mi-aplicacion:latest'



