//IN THIS FILE WE CAN PUT THE API DATA RESPONSE SAMPLES-

export const categories = [
  {
    id: 1,
    title: "International Buffet",
    description:
      "Our catering service offers an international buffet that will take you on a culinary journey around the world. Enjoy a wide variety of flavors and exquisite dishes from different cultures to delight your guests.",
    img: "../../public/images/image 7.png",
  },
  {
    id: 2,
    title: "Gourmet Cocktails",
    description:
      "Surprise your guests with our gourmet cocktails, crafted by expert mixologists. Each drink is a masterpiece of flavors and presentation, guaranteeing a unique experience for everyone.",
    img: "../../public/images/image 7.png",
  },
  {
    id: 3,
    title: "Grilled Barbecue",
    description:
      "Our grilled barbecue catering offers a selection of perfectly cooked meats and vegetables. The smoky aromas and flavors will make your event unforgettable.",
    img: "../../public/images/image 3.png",
  },
  {
    id: 4,
    title: "Artisanal Pastry",
    description:
      "Artisanal desserts are our specialty. Indulge in our variety of cakes, cookies, tarts, and sweets made with love and the finest ingredients.",
    img: "../../public/images/image 4.png",
  },
  {
    id: 5,
    title: "Vegan Catering",
    description:
      "Our vegan catering offers delicious and healthy options for those who prefer a plant-based diet. Fresh and natural flavors that will satisfy all your guests.",
    img: "../../public/images/image 5.png",
  },
  {
    id: 6,
    title: "Mediterranean Menu",
    description:
      "Enjoy the Mediterranean diet at your event with our specialized catering. Dishes with fresh and healthy ingredients inspired by Mediterranean cuisine.",
    img: "../../public/images/image 6.png",
  },
  {
    id: 7,
    title: "Sushi and Sashimi",
    description:
      "Our sushi and sashimi catering offers a selection of authentic Japanese cuisine. Delight in the flavors of the sea and the creativity of our chefs.",
    img: "../../public/images/image 7.png",
  },
  {
    id: 8,
    title: "Spanish Tapas",
    description:
      "Transport your guests to Spain with our selection of Spanish tapas. Intense and authentic flavors that will make you feel like you're in the heart of the Iberian Peninsula.",
    img: "../../public/images/image 8.png",
  },
  {
    id: 9,
    title: "Fusion Food",
    description:
      "A unique culinary experience that combines different traditions and culinary techniques. Discover surprising and creative flavors that will leave your guests amazed.",
    img: "../../public/images/image 9.png",
  },
  {
    id: 10,
    title: "Gourmet Breakfast",
    description:
      "Start your event with a gourmet breakfast that will awaken the senses. From healthy options to indulgent dishes, we have the perfect breakfast for your special occasion.",
    img: "../../public/images/image 7.png",
  },
  {
    id: 11,
    title: "Exquisite Seafood",
    description:
      "Indulge in our exquisite seafood catering that brings the flavors of the ocean to your event. Freshly caught seafood dishes that will leave your guests wanting more.",
    img: "../../public/images/image 7.png",
  },
  {
    id: 12,
    title: "Mexican Fiesta",
    description:
      "Celebrate with a vibrant Mexican fiesta at your event. Our catering showcases authentic Mexican cuisine with spicy flavors and traditional dishes.",
    img: "../../public/images/image 7.png",
  },
  {
    id: 13,
    title: "Mouthwatering BBQ",
    description:
      "Satisfy your guests' taste buds with our mouthwatering BBQ catering. Juicy meats, savory sauces, and sides that will make your event a memorable one.",
    img: "../../public/images/image 3.png",
  },
  {
    id: 14,
    title: "Decadent Desserts",
    description:
      "Treat yourself and your guests to our decadent desserts. From rich chocolate delights to fruity pastries, our dessert catering is a sweet dream come true.",
    img: "../../public/images/image 4.png",
  },
  {
    id: 15,
    title: "Plant-Based Delights",
    description:
      "Explore the world of plant-based delights with our vegan-friendly catering. Creative dishes that prove vegan food can be both delicious and nutritious.",
    img: "../../public/images/image 5.png",
  },
  {
    id: 16,
    title: "Asian Fusion",
    description:
      "Embark on a culinary journey through Asia with our Asian fusion catering. A fusion of flavors from different Asian cuisines that will delight your guests.",
    img: "../../public/images/image 6.png",
  },
  {
    id: 17,
    title: "Taste of Italy",
    description:
      "Experience the taste of Italy with our Italian-inspired catering. Pasta, pizza, and classic Italian dishes that capture the essence of Italian cuisine.",
    img: "../../public/images/image 7.png",
  },
  {
    id: 18,
    title: "French Delicacies",
    description:
      "Indulge in the elegance of French delicacies with our catering. From escargot to croissants, our French-inspired dishes will transport you to Paris.",
    img: "../../public/images/image 8.png",
  },
  {
    id: 19,
    title: "Exotic Flavors",
    description:
      "Discover the exotic flavors of our catering inspired by distant lands. Unique spices and ingredients that will add an adventurous touch to your event.",
    img: "../../public/images/image 9.png",
  },
  {
    id: 20,
    title: "Brunch Bonanza",
    description:
      "Make your event special with a brunch bonanza featuring a delightful array of breakfast and lunch favorites.",
    img: "../../public/images/image 7.png",
  },
];

export const cateringPackages = [
  {
    id: 1,
    name: "International Buffet",
    description: "Our catering service offers an international buffet that will take you on a culinary journey around the world. Enjoy a wide variety of flavors and exquisite dishes from different cultures to delight your guests.",
    numberDiners: 30,
    bundleImage: "../../public/images/image 1.png",
    galleryImages: [
      "../../public/images/image 11.png",
      "../../public/images/image 2.png",
      "../../public/images/image 3.png",
    ],
    categoryList: [1],
    starter: {
      id: 1,
      name: "Spring Rolls",
      type: "starter",
      description: "Crispy vegetable spring rolls served with sweet and sour sauce.",
      image: "../../public/images/image 11.png",
    },
    mainCourse: {
      id: 1,
      name: "Beef Stir-Fry",
      type: "main",
      description: "Tender beef strips stir-fried with vegetables and oyster sauce.",
      image: "../../public/images/image 2.png",
    },
    dessert: {
      id: 1,
      name: "Mango Sticky Rice",
      type: "dessert",
      description: "Sweet and creamy mango sticky rice, a Thai delicacy.",
      image: "../../public/images/image 3.png",
    },
    drinks: [
      {
        id: 1,
        name: "Thai Iced Tea",
        image: "../../public/images/image 5.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 2,
        name: "Coconut Water",
        image: "../../public/images/image 5.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 3,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 2,
    name: "Gourmet Cocktails",
    description: "Surprise your guests with our gourmet cocktails, crafted by expert mixologists. Each drink is a masterpiece of flavors and presentation, guaranteeing a unique experience for everyone.",
    numberDiners: 25,
    bundleImage: "../../public/images/image 2.png",
    galleryImages: [
      "../../public/images/image 4.png",
      "../../public/images/image 6.png",
      "../../public/images/image 2.png",
    ],
    categoryList: [2],
    starter: {
      id: 2,
      name: "Smoked Salmon Canapes",
      type: "starter",
      description: "Elegant canapes topped with smoked salmon and cream cheese.",
      image: "../../public/images/image 4.png",
    },
    mainCourse: {
      id: 2,
      name: "Lobster Bisque",
      type: "main",
      description: "Rich and creamy lobster bisque with a touch of sherry.",
      image: "../../public/images/image 6.png",
    },
    dessert: {
      id: 2,
      name: "Chocolate Fondue",
      type: "dessert",
      description: "Decadent chocolate fondue served with fresh fruit and marshmallows.",
      image: "../../public/images/image 2.png",
    },
    drinks: [
      {
        id: 4,
        name: "Cosmopolitan",
        image: "../../public/images/image 7.png",
        price: 200.0,
        amount: 180,
      },
      {
        id: 5,
        name: "Martini",
        image: "../../public/images/image 7.png",
        price: 180.0,
        amount: 150,
      },
      {
        id: 6,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 3,
    name: "Grilled Barbecue",
    description: "Our grilled barbecue catering offers a selection of perfectly cooked meats and vegetables. The smoky aromas and flavors will make your event unforgettable.",
    numberDiners: 40,
    bundleImage: "../../public/images/image 3.png",
    galleryImages: [
      "../../public/images/image 4.png",
      "../../public/images/image 11.png",
      "../../public/images/image 6.png",
    ],
    categoryList: [3],
    starter: {
      id: 3,
      name: "BBQ Chicken Wings",
      type: "starter",
      description: "Succulent BBQ chicken wings with a tangy glaze.",
      image: "../../public/images/image 4.png",
    },
    mainCourse: {
      id: 3,
      name: "Grilled Steak",
      type: "main",
      description: "Juicy grilled steak seasoned with our special blend of spices.",
      image: "../../public/images/image 11.png",
    },
    dessert: {
      id: 3,
      name: "Grilled Pineapple",
      type: "dessert",
      description: "Caramelized grilled pineapple for a sweet and refreshing treat.",
      image: "../../public/images/image 6.png",
    },
    drinks: [
      {
        id: 7,
        name: "Iced Tea",
        image: "../../public/images/image 5.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 8,
        name: "Lemonade",
        image: "../../public/images/image 5.png",
        price: 140.0,
        amount: 180,
      },
      {
        id: 9,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 4,
    name: "Artisanal Pastry",
    description: "Artisanal desserts are our specialty. Indulge in our variety of cakes, cookies, tarts, and sweets made with love and the finest ingredients.",
    numberDiners: 18,
    bundleImage: "../../public/images/image 4.png",
    galleryImages: [
      "../../public/images/image 7.png",
      "../../public/images/image 8.png",
      "../../public/images/image 9.png",
    ],
    categoryList: [4],
    starter: {
      id: 4,
      name: "Assorted Macarons",
      type: "starter",
      description: "Colorful and delicate macarons in various flavors.",
      image: "../../public/images/image 7.png",
    },
    mainCourse: {
      id: 4,
      name: "Raspberry Mousse Cake",
      type: "main",
      description: "Light and airy raspberry mousse cake with a sponge base.",
      image: "../../public/images/image 8.png",
    },
    dessert: {
      id: 4,
      name: "Chocolate Éclairs",
      type: "dessert",
      description: "Classic French éclairs filled with rich chocolate cream.",
      image: "../../public/images/image 9.png",
    },
    drinks: [
      {
        id: 10,
        name: "Coffee",
        image: "../../public/images/image 10.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 11,
        name: "Tea",
        image: "../../public/images/image 2.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 12,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 5,
    name: "Vegan Catering",
    description: "Our vegan catering offers delicious and healthy options for those who prefer a plant-based diet. Fresh and natural flavors that will satisfy all your guests.",
    numberDiners: 20,
    bundleImage: "../../public/images/image 5.png",
    galleryImages: [
      "../../public/images/image 4.png",
      "../../public/images/image 6.png",
      "../../public/images/image 12.png",
    ],
    categoryList: [5],
    starter: {
      id: 5,
      name: "Vegan Spring Rolls",
      type: "starter",
      description: "Crispy vegetable spring rolls served with vegan dipping sauce.",
      image: "../../public/images/image 4.png",
    },
    mainCourse: {
      id: 5,
      name: "Vegan Curry",
      type: "main",
      description: "Flavorful vegan curry with a medley of vegetables and tofu.",
      image: "../../public/images/image 6.png",
    },
    dessert: {
      id: 5,
      name: "Vegan Chocolate Cake",
      type: "dessert",
      description: "Decadent vegan chocolate cake made with plant-based ingredients.",
      image: "../../public/images/image 12.png",
    },
    drinks: [
      {
        id: 13,
        name: "Vegan Smoothie",
        image: "../../public/images/image 3.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 14,
        name: "Coconut Water",
        image: "../../public/images/image 5.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 15,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 6,
    name: "Mediterranean Menu",
    description: "Enjoy the Mediterranean diet at your event with our specialized catering. Dishes with fresh and healthy ingredients inspired by Mediterranean cuisine.",
    numberDiners: 25,
    bundleImage: "../../public/images/image 6.png",
    galleryImages: [
      "../../public/images/image 9.png",
      "../../public/images/image 10.png",
      "../../public/images/image 2.png",
    ],
    categoryList: [6],
    starter: {
      id: 6,
      name: "Greek Salad",
      type: "starter",
      description: "Refreshing Greek salad with tomatoes, cucumbers, olives, and feta cheese.",
      image: "../../public/images/image 9.png",
    },
    mainCourse: {
      id: 6,
      name: "Mediterranean Paella",
      type: "main",
      description: "Paella inspired by Mediterranean flavors with a mix of seafood and vegetables.",
      image: "../../public/images/image 10.png",
    },
    dessert: {
      id: 6,
      name: "Baklava",
      type: "dessert",
      description: "Traditional Greek dessert made with layers of phyllo pastry and nuts.",
      image: "../../public/images/image 2.png",
    },
    drinks: [
      {
        id: 16,
        name: "Sangria",
        image: "../../public/images/image 7.png",
        price: 200.0,
        amount: 180,
      },
      {
        id: 17,
        name: "Wine",
        image: "../../public/images/image 6.png",
        price: 180.0,
        amount: 150,
      },
      {
        id: 18,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 7,
    name: "Sushi and Sashimi",
    description: "Our sushi and sashimi catering offers a selection of authentic Japanese cuisine. Delight in the flavors of the sea and the creativity of our chefs.",
    numberDiners: 30,
    bundleImage: "../../public/images/image 7.png",
    galleryImages: [
      "../../public/images/image 11.png",
      "../../public/images/image 6.png",
      "../../public/images/image 3.png",
    ],
    categoryList: [7],
    starter: {
      id: 7,
      name: "Assorted Sushi Rolls",
      type: "starter",
      description: "A variety of sushi rolls with fresh fish and vegetables.",
      image: "../../public/images/image 11.png",
    },
    mainCourse: {
      id: 7,
      name: "Sashimi Platter",
      type: "main",
      description: "Delicate slices of raw fish served with wasabi and soy sauce.",
      image: "../../public/images/image 6.png",
    },
    dessert: {
      id: 7,
      name: "Green Tea Ice Cream",
      type: "dessert",
      description: "Creamy and fragrant green tea ice cream for a sweet finish.",
      image: "../../public/images/image 3.png",
    },
    drinks: [
      {
        id: 19,
        name: "Green Tea",
        image: "../../public/images/image 2.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 20,
        name: "Sake",
        image: "../../public/images/image 2.png",
        price: 220.0,
        amount: 100,
      },
      {
        id: 21,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 8,
    name: "Spanish Tapas",
    description: "Transport your guests to Spain with our selection of Spanish tapas. Intense and authentic flavors that will make you feel like you're in the heart of the Iberian Peninsula.",
    numberDiners: 20,
    bundleImage: "../../public/images/image 8.png",
    galleryImages: [
      "../../public/images/image 14.png",
      "../../public/images/image 10.png",
      "../../public/images/image 4.png",
    ],
    categoryList: [8],
    starter: {
      id: 8,
      name: "Patatas Bravas",
      type: "starter",
      description: "Crispy fried potatoes served with spicy tomato sauce.",
      image: "../../public/images/image 14.png",
    },
    mainCourse: {
      id: 8,
      name: "Paella Valenciana",
      type: "main",
      description: "Traditional Valencian paella with a medley of meat and vegetables.",
      image: "../../public/images/image 10.png",
    },
    dessert: {
      id: 8,
      name: "Churros",
      type: "dessert",
      description: "Spanish churros served with chocolate dipping sauce.",
      image: "../../public/images/image 4.png",
    },
    drinks: [
      {
        id: 22,
        name: "Sangria",
        image: "../../public/images/image 7.png",
        price: 200.0,
        amount: 180,
      },
      {
        id: 23,
        name: "Spanish Wine",
        image: "../../public/images/image 6.png",
        price: 180.0,
        amount: 150,
      },
      {
        id: 24,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 9,
    name: "Wedding Package",
    description: "Celebrate your special day with our elegant wedding package, featuring a curated menu and exquisite details to make your wedding unforgettable.",
    numberDiners: 100,
    bundleImage: "../../public/images/image 9.png",
    galleryImages: [
      "../../public/images/image 11.png",
      "../../public/images/image 4.png",
      "../../public/images/image 9.png",
    ],
    categoryList: [1],
    starter: {
      id: 9,
      name: "Stuffed Mushrooms",
      type: "starter",
      description: "Mushroom caps stuffed with a savory mixture of cheese and herbs.",
      image: "../../public/images/image 11.png",
    },
    mainCourse: {
      id: 9,
      name: "Beef Tenderloin",
      type: "main",
      description: "Tender beef tenderloin cooked to perfection and served with a red wine reduction.",
      image: "../../public/images/image 4.png",
    },
    dessert: {
      id: 9,
      name: "Wedding Cake",
      type: "dessert",
      description: "Elegant wedding cake with layers of sponge and buttercream.",
      image: "../../public/images/image 9.png",
    },
    drinks: [
      {
        id: 25,
        name: "Champagne",
        image: "../../public/images/image 7.png",
        price: 300.0,
        amount: 120,
      },
      {
        id: 26,
        name: "Wine",
        image: "../../public/images/image 6.png",
        price: 180.0,
        amount: 150,
      },
      {
        id: 27,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 10,
    name: "Mexican Fiesta",
    description: "Spice up your event with a Mexican fiesta! Our menu features authentic Mexican dishes that will transport your guests to the colorful streets of Mexico.",
    numberDiners: 40,
    bundleImage: "../../public/images/image 10.png",
    galleryImages: [
      "../../public/images/image 3.png",
      "../../public/images/image 9.png",
      "../../public/images/image 7.png",
    ],
    categoryList: [1, 2],
    starter: {
      id: 10,
      name: "Guacamole and Chips",
      type: "starter",
      description: "Fresh guacamole served with crispy tortilla chips.",
      image: "../../public/images/image 3.png",
    },
    mainCourse: {
      id: 10,
      name: "Chicken Fajitas",
      type: "main",
      description: "Sizzling chicken fajitas with bell peppers and onions.",
      image: "../../public/images/image 9.png",
    },
    dessert: {
      id: 10,
      name: "Churros",
      type: "dessert",
      description: "Traditional Mexican churros dusted with cinnamon sugar.",
      image: "../../public/images/image 7.png",
    },
    drinks: [
      {
        id: 28,
        name: "Margarita",
        image: "../../public/images/image 10.png",
        price: 220.0,
        amount: 100,
      },
      {
        id: 29,
        name: "Agua Fresca",
        image: "../../public/images/image 10.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 30,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 11,
    name: "Asian Fusion",
    description: "Experience the best of Asian flavors with our fusion menu that combines the tastes of different Asian cuisines.",
    numberDiners: 35,
    bundleImage: "../../public/images/image 11.png",
    galleryImages: [
      "../../public/images/image 12.png",
      "../../public/images/image 5.png",
      "../../public/images/image 14.png",
    ],
    categoryList: [1, 3],
    starter: {
      id: 11,
      name: "Sushi Burrito",
      type: "starter",
      description: "A sushi roll in the form of a burrito, filled with your choice of fresh ingredients.",
      image: "../../public/images/image 12.png",
    },
    mainCourse: {
      id: 11,
      name: "Korean BBQ Ribs",
      type: "main",
      description: "Tender and flavorful Korean BBQ ribs with a spicy marinade.",
      image: "../../public/images/image 5.png",
    },
    dessert: {
      id: 11,
      name: "Mango Sticky Rice",
      type: "dessert",
      description: "Sweet and creamy mango sticky rice, a Thai delicacy.",
      image: "../../public/images/image 14.png",
    },
    drinks: [
      {
        id: 31,
        name: "Bubble Tea",
        image: "../../public/images/image 3.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 32,
        name: "Thai Iced Tea",
        image: "../../public/images/image 5.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 33,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 12,
    name: "Vegetarian Delight",
    description: "Our vegetarian menu is a delightful selection of dishes that showcase the versatility and flavors of plant-based ingredients.",
    numberDiners: 25,
    bundleImage: "../../public/images/image 12.png",
    galleryImages: [
      "../../public/images/image 13.png",
      "../../public/images/image 6.png",
      "../../public/images/image 10.png",
    ],
    categoryList: [1, 5],
    starter: {
      id: 12,
      name: "Stuffed Bell Peppers",
      type: "starter",
      description: "Bell peppers stuffed with a savory mixture of quinoa and vegetables.",
      image: "../../public/images/image 13.png",
    },
    mainCourse: {
      id: 12,
      name: "Eggplant Parmesan",
      type: "main",
      description: "Layers of breaded eggplant and melted cheese in a rich tomato sauce.",
      image: "../../public/images/image 6.png",
    },
    dessert: {
      id: 12,
      name: "Vegan Chocolate Cake",
      type: "dessert",
      description: "Decadent vegan chocolate cake made with plant-based ingredients.",
      image: "../../public/images/image 10.png",
    },
    drinks: [
      {
        id: 34,
        name: "Sparkling Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
      {
        id: 35,
        name: "Herbal Tea",
        image: "../../public/images/image 2.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 36,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 13,
    name: "Healthy Boost",
    description: "Promote health and well-being with our nourishing and nutritious menu, designed to energize and revitalize.",
    numberDiners: 30,
    bundleImage: "../../public/images/image 13.png",
    galleryImages: [
      "../../public/images/image 4.png",
      "../../public/images/image 5.png",
      "../../public/images/image 6.png",
    ],
    categoryList: [1, 4],
    starter: {
      id: 13,
      name: "Quinoa Salad",
      type: "starter",
      description: "Nutrient-rich quinoa salad with colorful vegetables and herbs.",
      image: "../../public/images/image 4.png",
    },
    mainCourse: {
      id: 13,
      name: "Grilled Salmon",
      type: "main",
      description: "Healthy and flavorful grilled salmon with a lemon herb sauce.",
      image: "../../public/images/image 5.png",
    },
    dessert: {
      id: 13,
      name: "Fresh Fruit Platter",
      type: "dessert",
      description: "A delightful platter of fresh and seasonal fruits.",
      image: "../../public/images/image 6.png",
    },
    drinks: [
      {
        id: 37,
        name: "Detox Water",
        image: "../../public/images/image 9.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 38,
        name: "Herbal Tea",
        image: "../../public/images/image 2.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 39,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 14,
    name: "Tropical Paradise",
    description: "Transport your guests to a tropical paradise with our menu featuring exotic flavors and fresh ingredients.",
    numberDiners: 40,
    bundleImage: "../../public/images/image 14.png",
    galleryImages: [
      "../../public/images/image 3.png",
      "../../public/images/image 15.png",
      "../../public/images/image 9.png",
    ],
    categoryList: [1, 6],
    starter: {
      id: 14,
      name: "Tropical Ceviche",
      type: "starter",
      description: "A refreshing and tangy ceviche with tropical fruits and seafood.",
      image: "../../public/images/image 3.png",
    },
    mainCourse: {
      id: 14,
      name: "Caribbean Jerk Chicken",
      type: "main",
      description: "Tender chicken marinated in Caribbean spices and grilled to perfection.",
      image: "../../public/images/image 15.png",
    },
    dessert: {
      id: 14,
      name: "Coconut Flan",
      type: "dessert",
      description: "Creamy coconut flan with a caramelized sugar topping.",
      image: "../../public/images/image 9.png",
    },
    drinks: [
      {
        id: 40,
        name: "Piña Colada",
        image: "../../public/images/image 4.png",
        price: 220.0,
        amount: 100,
      },
      {
        id: 41,
        name: "Tropical Smoothie",
        image: "../../public/images/image 3.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 42,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 15,
    name: "Classic Italian",
    description: "Indulge in the flavors of Italy with our classic Italian menu featuring beloved dishes from the heart of Italy.",
    numberDiners: 35,
    bundleImage: "../../public/images/image 15.png",
    galleryImages: [
      "../../public/images/image 10.png",
      "../../public/images/image 13.png",
      "../../public/images/image 12.png",
    ],
    categoryList: [1, 3],
    starter: {
      id: 15,
      name: "Caprese Salad",
      type: "starter",
      description: "A simple and delicious salad with tomatoes, fresh mozzarella, and basil.",
      image: "../../public/images/image 10.png",
    },
    mainCourse: {
      id: 15,
      name: "Spaghetti Carbonara",
      type: "main",
      description: "Classic spaghetti carbonara with eggs, cheese, and pancetta.",
      image: "../../public/images/image 13.png",
    },
    dessert: {
      id: 15,
      name: "Tiramisu",
      type: "dessert",
      description: "The quintessential Italian dessert made with layers of coffee-soaked ladyfingers and mascarpone cheese.",
      image: "../../public/images/image 12.png",
    },
    drinks: [
      {
        id: 43,
        name: "Chianti Wine",
        image: "../../public/images/image 6.png",
        price: 180.0,
        amount: 150,
      },
      {
        id: 44,
        name: "Espresso",
        image: "../../public/images/image 4.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 45,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 16,
    name: "Sweet Treats",
    description: "Satisfy your sweet tooth with our delightful assortment of desserts and treats that are sure to please.",
    numberDiners: 20,
    bundleImage: "../../public/images/image 16.png",
    galleryImages: [
      "../../public/images/image 14.png",
      "../../public/images/image 10.png",
      "../../public/images/image 8.png",
    ],
    categoryList: [4],
    starter: {
      id: 16,
      name: "Assorted Macarons",
      type: "starter",
      description: "Colorful and delicate macarons in various flavors.",
      image: "../../public/images/image 14.png",
    },
    mainCourse: {
      id: 16,
      name: "Raspberry Mousse Cake",
      type: "main",
      description: "Light and airy raspberry mousse cake with a sponge base.",
      image: "../../public/images/image 10.png",
    },
    dessert: {
      id: 16,
      name: "Chocolate Fondue",
      type: "dessert",
      description: "Decadent chocolate fondue served with fresh fruit and marshmallows.",
      image: "../../public/images/image 8.png",
    },
    drinks: [
      {
        id: 46,
        name: "Hot Chocolate",
        image: "../../public/images/image 4.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 47,
        name: "Milkshake",
        image: "../../public/images/image 3.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 48,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 17,
    name: "Farm-to-Table",
    description: "Experience the freshest ingredients and seasonal flavors with our farm-to-table menu that celebrates local produce.",
    numberDiners: 30,
    bundleImage: "../../public/images/image 17.png",
    galleryImages: [
      "../../public/images/image 9.png",
      "../../public/images/image 7.png",
      "../../public/images/image 10.png",
    ],
    categoryList: [2, 3],
    starter: {
      id: 17,
      name: "Roasted Vegetable Salad",
      type: "starter",
      description: "A medley of roasted vegetables tossed in a balsamic vinaigrette.",
      image: "../../public/images/image 9.png",
    },
    mainCourse: {
      id: 17,
      name: "Herb-Roasted Chicken",
      type: "main",
      description: "Tender herb-roasted chicken served with a side of seasonal vegetables.",
      image: "../../public/images/image 7.png",
    },
    dessert: {
      id: 17,
      name: "Fruit Crisp",
      type: "dessert",
      description: "Warm fruit crisp topped with a crunchy oat crumble.",
      image: "../../public/images/image 10.png",
    },
    drinks: [
      {
        id: 49,
        name: "Sparkling Lemonade",
        image: "../../public/images/image 5.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 50,
        name: "Herbal Iced Tea",
        image: "../../public/images/image 2.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 51,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 18,
    name: "Seafood Feast",
    description: "Delight in a bountiful seafood feast with our menu featuring the freshest catches from the sea.",
    numberDiners: 25,
    bundleImage: "../../public/images/image 18.png",
    galleryImages: [
      "../../public/images/image 11.png",
      "../../public/images/image 15.png",
      "../../public/images/image 9.png",
    ],
    categoryList: [3],
    starter: {
      id: 18,
      name: "Seafood Ceviche",
      type: "starter",
      description: "A refreshing and tangy ceviche with a medley of seafood.",
      image: "../../public/images/image 11.png",
    },
    mainCourse: {
      id: 18,
      name: "Grilled Lobster",
      type: "main",
      description: "Juicy lobster tails grilled to perfection and served with lemon butter.",
      image: "../../public/images/image 15.png",
    },
    dessert: {
      id: 18,
      name: "Key Lime Pie",
      type: "dessert",
      description: "A zesty and creamy key lime pie with a graham cracker crust.",
      image: "../../public/images/image 9.png",
    },
    drinks: [
      {
        id: 52,
        name: "Sea Breeze Cocktail",
        image: "../../public/images/image 10.png",
        price: 220.0,
        amount: 100,
      },
      {
        id: 53,
        name: "Citrus Punch",
        image: "../../public/images/image 4.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 54,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 19,
    name: "Garden Party",
    description: "Host a charming garden party with our delightful menu that showcases the best of seasonal produce.",
    numberDiners: 20,
    bundleImage: "../../public/images/image 19.png",
    galleryImages: [
      "../../public/images/image 14.png",
      "../../public/images/image 8.png",
      "../../public/images/image 12.png",
    ],
    categoryList: [2, 4],
    starter: {
      id: 19,
      name: "Caprese Skewers",
      type: "starter",
      description: "Fresh mozzarella and cherry tomatoes skewers drizzled with balsamic glaze.",
      image: "../../public/images/image 14.png",
    },
    mainCourse: {
      id: 19,
      name: "Grilled Vegetable Tart",
      type: "main",
      description: "A savory tart filled with grilled vegetables and goat cheese.",
      image: "../../public/images/image 8.png",
    },
    dessert: {
      id: 19,
      name: "Lemon Bars",
      type: "dessert",
      description: "Zesty lemon bars with a buttery shortbread crust.",
      image: "../../public/images/image 12.png",
    },
    drinks: [
      {
        id: 55,
        name: "Sparkling Lemonade",
        image: "../../public/images/image 5.png",
        price: 180.0,
        amount: 200,
      },
      {
        id: 56,
        name: "Herbal Iced Tea",
        image: "../../public/images/image 2.png",
        price: 160.0,
        amount: 150,
      },
      {
        id: 57,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
  {
    id: 20,
    name: "Holiday Special",
    description: "Celebrate the holiday season with our special menu featuring festive and comforting dishes.",
    numberDiners: 30,
    bundleImage: "../../public/images/image 20.png",
    galleryImages: [
      "../../public/images/image 13.png",
      "../../public/images/image 9.png",
      "../../public/images/image 11.png",
    ],
    categoryList: [1, 5],
    starter: {
      id: 20,
      name: "Cheese Fondue",
      type: "starter",
      description: "A cozy and indulgent cheese fondue served with bread and vegetables for dipping.",
      image: "../../public/images/image 13.png",
    },
    mainCourse: {
      id: 20,
      name: "Roast Turkey",
      type: "main",
      description: "Juicy roast turkey with all the traditional holiday trimmings.",
      image: "../../public/images/image 9.png",
    },
    dessert: {
      id: 20,
      name: "Gingerbread Cookies",
      type: "dessert",
      description: "Delicious gingerbread cookies in festive shapes and decorations.",
      image: "../../public/images/image 11.png",
    },
    drinks: [
      {
        id: 58,
        name: "Eggnog",
        image: "../../public/images/image 10.png",
        price: 200.0,
        amount: 180,
      },
      {
        id: 59,
        name: "Mulled Wine",
        image: "../../public/images/image 6.png",
        price: 180.0,
        amount: 150,
      },
      {
        id: 60,
        name: "Mineral Water",
        image: "../../public/images/image 8.png",
        price: 120.0,
        amount: 250,
      },
    ],
  },
];