spring:
  datasource:
    url: jdbc:mysql://localhost:3306/catering
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

#S3
cloud:
  aws:
    region:
      static: us-east-1
    stack:
      auto: false
    credentials:
      access-key: AKIAY3PLHSUJIHZD7YVM
      secret-key: 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
# Desactivar Spring Security
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
